### ISSUE TITLE
Mobile Nav Menu

### ISSUE THREAD

**Issue by theilman7** [baltimorecounty/restaurant-week#62] opened 2018-05-17 16:02 UTC
When opening the mobile nav on iPad, the menu does not open the full height of the page, like what it does on mobile. In addition, if you scroll down the page on mobile so the hamburger icon is just to the top edge of the page and click, the menu doesn't expand or readjust so it is covering the bottom of the screen.

**Comment by martypowell** [comment] 2018-05-17 17:26
@theilman7 Right now this is a nice to have, there are some challenges with the way the page is laid out to achieve this look. JavaScript will probably have to get involved.

**Comment by martypowell** [comment] 2018-05-21 12:48
duplicate of #39

**Closed as completed by martypowell** 2018-05-21 12:48 UTC
